### ISSUE TITLE
A compile error on UE5.7.4 and a feasible solution

### ISSUE THREAD

**Issue by Carlos0902** [PRQELT/Autonomix#2]
The error comes from: Autonomix\Source\AutonomixActions\Private\Widget\AutonomixWidgetActions.cpp: 1233, where the integer placeholder '%d' of
`Result.ResultMessage = FString::Printf(TEXT("Set font on '%s': size=%d%s%s."),` raises an error C7595 “UE::Core::Private::FormatStringSan::TCheckedFormatStringPrivate<FString::FmtCharType,const FString::ElementType *,float,const FString::ElementType *,const FString::ElementType *>::TCheckedFormatStringPrivate”.

A feasible solution is changing it to a float:
`Result.ResultMessage = FString::Printf(TEXT("Set font on '%s': size=%.0f%s%s.")`,

This works on my UE5.7.4.
